package io.github.xxfast.decompose.router.screens

const val BACK_BUTTON_TAG = "back"
const val BOTTOM_NAV_BAR = "bottomNav"
const val BOTTOM_NAV_PAGES = "bottomNavPages"
const val BOTTOM_NAV_SLOT = "bottomNavSlot"
const val BOTTOM_NAV_STACK = "bottomNavStack"
const val BOTTOM_SHEET = "bottomSheet"
const val BUTTON_BOTTOM_SHEET = "btnBottomSheet"
const val BUTTON_DIALOG = "btnDialog"
const val DETAILS_TAG = "details"
const val DIALOG = "dialog"
const val FAB_ADD = "fabAdd"
const val LIST_TAG = "list"
const val PAGER = "pager"
const val TITLE_BAR_TAG = "titleBar"
const val TOOLBAR_TAG = "toolbar"
