package io.github.xxfast.decompose.router.screens

const val BUTTON_BACK = "back"
const val BUTTON_FORWARD = "forward"
const val BOTTOM_NAV_BAR = "bottomNav"
const val BOTTOM_NAV_PAGES = "bottomNavPages"
const val BOTTOM_NAV_SLOT = "bottomNavSlot"
const val BOTTOM_NAV_STACK = "bottomNavStack"
const val BOTTOM_NAV_ITEMS = "bottonNavItems"
const val BOTTOM_SHEET = "bottomSheet"
const val BUTTON_BOTTOM_SHEET = "btnBottomSheet"
const val BUTTON_DIALOG = "btnDialog"
const val DETAILS = "details"
const val DIALOG = "dialog"
const val FAB_ADD = "fabAdd"
const val LIST_TAG = "list"
const val PAGER = "pager"
const val TITLE_BAR = "titleBar"
const val TOOLBAR = "toolbar"
